### ISSUE TITLE
Saved tsv's re-introduce escaping of quotes

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/CorporaCreator#61]

**Comment by simnotes** [comment]
I Think you have add *import csv* on top of the file. Otherwise, you cannot use `csv.QUOTE_NONE`

**Comment by kdavis-mozilla** [comment]
OK, will change.

Could you accept the repo invite? I think you need to do so before I can ask for you to review.

**Comment by simnotes** [comment]
Invitation accepted. Thanks!
