### ISSUE TITLE
Consider changing name "valid.csv" and "invalid.csv"

### ISSUE THREAD

**Issue by JRMeyer** [mozilla/CorporaCreator#83]
Given that "dev" and "valid" are used interchangeably in the machine learning world to refer to the held-out dataset which is used for early stopping, I think having a `valid.csv` as well as a `dev.csv` will lead to confusion. 

Given that "invalid.csv" also exists, and the filenames should make obvious that "valid.csv" and "invalid.csv" are complementary sets, I suggest the following names:

| **valid.csv** | **invalid.csv** |
|-----|-----|
|validated.csv|invalidated.csv|
|accurate.csv|inaccurate.csv|
|correct.csv|incorrect.csv|
|confirmed.csv|uncomfirmed.csv|
|verified.csv|unverified.csv|
|validated_transcripts.csv|invalidated_transcripts.csv|
|accurate_transcripts.csv|inaccurate_transcripts.csv|
|correct_transcripts.csv|incorrect_transcripts.csv|
|confirmed_transcripts.csv|unconfirmed_transcripts.csv|
|verified_transcripts.csv|unverified_transcripts.csv|

**Comment by kdavis-mozilla** [comment]
What about keeping it simple with validated.csv and invalidated.csv?
