### ISSUE TITLE
train/test/dev.tsv too small compared to validated

### ISSUE THREAD

**Issue by bayethiernodiop** [mozilla/CorporaCreator#96]
Hello, in my validated.tsv i have about 8000 rows but in my train.tsv i only have about 300 and the same in my test and dev .tsv files. can any one explain why please

**Comment by kdavis-mozilla** [comment]
The splits are calculated here [_calculate_data_set_sizes()](https://github.com/mozilla/CorporaCreator/blob/1d9be5e9279f4a2dcbf68e125fe9d614b69278e2/src/corporacreator/corpus.py#L107).

Do you have an idea for another way of splitting?

**Comment by bayethiernodiop** [comment]
hummm ok, where does total_size come from? is it the same than the size of the audios validated?

**Comment by kdavis-mozilla** [comment]
[Here](https://github.com/mozilla/CorporaCreator/blob/1d9be5e9279f4a2dcbf68e125fe9d614b69278e2/src/corporacreator/corpus.py#L87)

**Comment by bayethiernodiop** [comment]
thanks a lot for you hep. but here what i dont understand since the total size is the size of the validated data how come i have such small training/dev and test size given the size of my validated data. i think it has to be with the number of speakers in my data which is about 30 i think but i am quite lost.

**Comment by bayethiernodiop** [comment]
i think this is caused by [this](https://github.com/mozilla/CorporaCreator/blob/1d9be5e9279f4a2dcbf68e125fe9d614b69278e2/src/corporacreator/corpus.py#L81)  because now [this](https://github.com/mozilla/CorporaCreator/blob/1d9be5e9279f4a2dcbf68e125fe9d614b69278e2/src/corporacreator/corpus.py#L87) no longer give the actual number of validated audios which is about 8000. I think this parameter self.args.duplicate_sentence_count is what eliminate most of the recordings in the validated ones. can you help here.
P.S since i am in a close domain with limited keysentences i have many repeated recording of the same sentences by different users

**Comment by kdavis-mozilla** [comment]
Yes, duplicate sentences are not allowed by default. But there is a [command line argument](https://github.com/mozilla/CorporaCreator/blob/master/src/corporacreator/argparse.py#L83) that lets you to set the number of duplicates allowed.

**Comment by bayethiernodiop** [comment]
Does this mean we cant have two recordings of the same sentence in the dataset ?

**Comment by kdavis-mozilla** [comment]
No. You can call corpora creator with `--duplicate-sentence-count 1000000` if you want.

**Comment by bayethiernodiop** [comment]
hummm ok. but this is very weired for me.  because normally we want diversity so we wanna have different users recording the same sentences so that the model is more generalized. Am i missing something ? can you please tell me why this is the default choice i mean the benefit.

**Comment by kdavis-mozilla** [comment]
There are at least two dimensions of diversity. Speaker diversity and sentence diversity.

We want both and to have both a data set should consist of unique sentences spoken by as many people as possible. Thus the default. But you don't have to use the default.

**Comment by bayethiernodiop** [comment]
ah i see you are right this is a good default in non colosed domains with many unique sentences. Thanks a lot for your responses.
